tazjin/nixery

build-registry-image.nix
Introduce an empty runtime configuration object in each built layer.
This is required because Kubernetes expects the configuration to be
present (even if it's just empty values).
Providing an empty configuration will make Docker's API return a full
configuration struct with default (i.e. empty) values rather than
`null`, which works for Kubernetes.
This fixes issue #1. See the issue for additional details.
=> fix(nix): Add empty image config to allow k8s usage

README.md, build-registry-image.nix, default.nix, main.go
See issue #3 for background.
---------
This implements support for importing the Nix package set used when building images from various different locations, such as custom git repositories or filesystem paths, in addition to the standard Nix channels.
Users can configure from where Nixery should import package sets by setting one of several environment variables.
This fixes #3.
=> Implement support for custom package sets

build-registry-image.nix, main.go
Ensures that errors are returned with actual status codes, for example for cases where packages could not be found (-> 404).
See individual commits for details. This fixes #11.
=> Return more structured error information to registry clients

static/index.html
People should not start depending on the demo instance. There have
been discussions around making a NixOS-official instance, but the
project needs to mature a little bit first.
=> Note that the demo instance is just a demo

default.nix
Mea culpa! My current local test setup does not cover the final image, and I should probably fix that.
=> Fix missing launch script dependencies

.travis.yml, default.nix
Makes use of [Cachix](https://cachix.org) for Nix-caching. See commits for details.
=> Use Cachix for Nix artifact caching in CI

main.go
This affected the public instance which is still running without URL signing.
To catch this stuff I've now set up monitoring on the public instance:
The public instance should eventually transition to signed URls, too.
=> fix(go): Fix breakage in unsigned URLs

build-registry-image.nix, default.nix, docs/default.nix
`buildLayeredImage` has a notion of maximum image layers, which determine how well the algorithm can group derivations that should be in their own layers to avoid cache busts.
Setting this number involves a tradeoff where we pay for better caching characteristics by sacrificing extensibility (the closer it gets to Docker's maximum of 125, the fewer additional layers users can add on top) and pull speed (concurrency limits during pulls might impact large pulls). The latter two don't really matter much for Nixery's intended use-cases though, so it's worth experimenting with this.
Tangentially related to #15.
=> Significantly increase maximum number of layers

.travis.yml
This test, after performing the usual Nixery build, loads the built
image into Docker, runs it, pulls an image from Nixery and runs that
image.
Currently tested:
This covers most parts of the flow already!
----------
To make this work, there is some configuration on the Travis side.
Most importantly, the following environment variables have special
values:
* `GOOGLE_KEY`: This is set to a base64-encoded service account key to
be used in the test.
* `GCS_SIGNING_PEM`: This is set to a base64-encoded signing key (in
PEM) that is used for signing URLs.
Both of these are available to all branches in the Nixery repository.
=> Add an integration test that runs on Travis

server/builder/builder.go
These probably should be part of every container image by default, but
adding it to the "shell" convenience name probably is our best bet for
now.
=> Add iana-etc and cacert to the shell convenience package

server/builder/builder.go
Before this change, Nixery would pass on the image name unmodified to
Nix which would lead it to cache-bust the manifest and configuration
layers for images that are content-identical but have different
package ordering.
Note: While testing this I also came across a new example of #39 and verified that Docker is indeed pulling the same layers, next step is to dig into the Docker code and figure out what they use to determine if a layer is cached.
This fixes #38.
=> Sort requested packages in image name & spec

default.nix
This is required by git in cases where Nixery is configured with a
custom git repository.
I've also added a shell back into the image to make debugging a
running Nixery easier. It turns out some of the dependencies already
pull in bash anyways, so this is just surfacing it to $PATH.
=> Ensure root user is known inside of container

.travis.yml, build-image/default.nix, build-image/load-pkgs.nix, default.nix, server/builder/builder.go, server/builder/cache.go, server/config/config.go, server/config/pkgsource.go, server/main.go
This pull request implements caching of manifests to the bucket used for layer storage. Manifests are cached based on a key that is determined as a combination of the package source and image contents.
Note that manifests will only be cached for package sources which are **not** moving targets, i.e. either a full git commit hash of a private package repository or of nixpkgs.
This prevents rebuilds of identical manifests between different instances of Nixery.
See individual commits for details. This relates to #50 in that it implements the first step of the new proposed build process.
=> Implement instance-independent manifest caching

.travis.yml, README.md, build-image/build-image.nix, build-image/default.nix, default.nix, docs/default.nix, server/builder/builder.go, server/config/config.go
See individual commits.
I experimented with doing stuff like automatically templating `lib.version` into the popularity URL, but that breaks for anything other than non-trivial use cases.
This fixes #53.
=> Add configuration option for the popularity URL

.travis.yml, build-image/build-image.nix, server/builder/archive.go, server/builder/builder.go, server/manifest/manifest.go
This needs some evaluation (and maybe feature-gating). There are a couple of noteworthy things:
* Cache compatibility is broken (essentially Nixery's bucket needs to be wiped if moving from non-gzip to gzip - in theory the layer objects can be kept around, but a user would probably want all manifests & builds purged to make sure that compressed versions are used)
* Whether the tradeoff between CPU time vs. upload time is worth it might be dependent on the situation (e.g. inside GCP, the additional data size might not matter that much if it's only moving between nodes & GCS)
This fixes #62
=> Apply GZIP compression to all image layers

default.nix
Some Nix download mechanisms will add a second hash in the store path,
which had been added to the source hash output (breaking argument
interpolation).
=> fix(build): Only take the first matching hash for source hashing

README.md, docs/src/run-your-own.md, server/config/config.go
See individual commits for details.
This fixes #36.
cc: @srhb
=> Use service account credentials for signing GCS URLs

.travis.yml, build-image/build-image.nix, default.nix, server/builder/builder.go, server/manifest/manifest.go
See individual commits.
This fixes #13.
=> Introduce support for building ARM architecture images

server/builder/builder.go, server/builder/builder_test.go
Without this an image only using `shell` did not work. This regression was introduced in #13 and is now covered by tests.
=> Fix broken builds if users specify only meta-packages

builder/builder.go
The `cmd` and `image` fields ended up swapped in the log output here.
=> fix(builder): Fix minor logging switcharoo

popcount/default.nix
Previously, this was failing as follows:
```
these derivations will be built:
/nix/store/7rbrf06phkiyz31dwpq88x920zjhnw0c-nixery-popcount.drv
building '/nix/store/7rbrf06phkiyz31dwpq88x920zjhnw0c-nixery-popcount.drv'...
building
warning: GOPATH set to GOROOT (/nix/store/4859cp1v7zqcqh43jkqsayl4wrz3g6hp-go-1.13.4/share/go) has no effect
failed to initialize build cache at /homeless-shelter/.cache/go-build: mkdir /homeless-shelter: permission denied
builder for '/nix/store/7rbrf06phkiyz31dwpq88x920zjhnw0c-nixery-popcount.drv' failed with exit code 1
error: build of '/nix/store/7rbrf06phkiyz31dwpq88x920zjhnw0c-nixery-popcount.drv' failed
```
=> fix(popcount): Fix nix-build -A nixery-popcount

docs/src/caching.md, docs/src/nixery.md, docs/src/run-your-own.md, prepare-image/prepare-image.nix
Use a NixOS / NixPkgs release that's actually being supported and regularly updated.
- One might want to pull containers with up-to-date software from nixery. (I do.)
- NixOS 19.03 has been unsupported for ~ half a year now.
- Section [Which revision of nixpkgs is used for the builds?](https://nixery.dev/nixery.html#which-revision-of-nixpkgs-is-used-for-the-builds) in the FAQ claims about [nixery.dev](https://nixery.dev):
> The channel is updated several times a day.
That is only useful if the upstream channel content actually changes now and then. NixPkgs branch [`release-19.03`](https://github.com/NixOS/nixpkgs/commits/release-19.03) has recently received only around 3 changes per month.
:warning: This change is completely untested, as I don't have a Nixery instance of my own.
=> chore(nix): update channel 19.03 -> 20.03

config/pkgsource.go, main.go
There is a new handler coming up to fix #102 and I want to avoid falling into the classic Go trap of creating thousand-line functions.
=> refactor(main): Split HTTP handlers into separate functions

main.go, storage/filesystem.go, storage/gcs.go, storage/storage.go
This series of changes makes it possible for clients to fetch (previously created) manifests by digest. This allows for compatibility with containerd.
Please see the individual commits for details.
This fixes #102 
cc @jonjohnsonjr
=> Implement fetching of manifests by digest

builder/builder.go, builder/cache.go, main.go, manifest/manifest.go, storage/filesystem.go, storage/gcs.go, storage/storage.go
Extends storage.Persist to accept a Content-Type argument, which in
the GCS backend is persisted with the object to ensure that the object
is served back with this content-type.
This is not yet implemented for the filesystem backend, where the
parameter is simply ignored.
This should help in the case of clients which expect the returned
objects to have content-types set when, for example, fetching layers
by digest.
cc @jonjohnsonjr
=> feat(storage): Add support for content-types (GCS only)

prepare-image/load-pkgs.nix
It looks like NixPkgs channels have moved. Fixing this URL allows
using nixos-20.09, for instance.
=> chore(nix): update channel URL

.github/workflows/build-and-test.yaml
Travis is being deprecated, and this might be the best option for now. In fact the current Travis checks don't work anymore.
=> Configure Github Actions as the CI system

.github/workflows/build-and-test.yaml
We don't intend to label, authenticate or whatever with the
GITHUB_TOKEN, so there's not really a reason to give any broader
permissions than the defaults.
=> feat(ci): remove unneeded permissions: read-all

.github/workflows/build-and-test.yaml
* remove a step that was not supposed to be committed ("Do we have Docker?")
* remove setup of old temporary storage directory (now done in integration script test instead)
* skip creation of out-link for initial Nixery build (to avoid cache-busting on the second build)
=> chore(ci): Remove unnecessary commands from new CI setup

.gitignore, scripts/integration-test.sh
With https://github.com/google/nixery/pull/127, nixery will use extended
attributes to store metadata (when using local storage).
Right now, our integration test mounts a tmpfs to /var/cache/nixery.
However, *user* xattrs aren't supported with tmpfs [1], so setting
xattrs would fail.
To workaround this, use a folder in the current working directory and
hope it's backed by something supporting user xattrs (which is the case
for GitHub Actions).
[1]: https://man7.org/linux/man-pages/man5/tmpfs.5.html#NOTES
=> feat(ci): don't mount /var/cache/nixery from tmpfs into docker container

default.nix, go.mod, go.sum, storage/filesystem.go
After the discussion in #116, this stores the blob content types
in extended attributes when using the filesystem backend.
If the underlying filesystem doesn't support extended attributes,
storing blobs won't work; also, if extended attributes get removed,
blobs won't be served anymore. We can relax this behavior if
needed (i.e. log errors but still accept to store or serve blobs).
However, since the Docker Engine (and possibly other container
engines) won't accept to pull images from a registry that doesn't
use correct content types for manifest files, it could be argued
that it's better to give a hard fail. (Otherwise, the container
engine gives cryptic error messages like "missing signature key".)
I can change that behavior (and log errors but still store/serve
blobs to the filesystem) …
=> feat(storage): Store blob content-type in extended attributes

README.md
Moves the build badge to point at Github Actions, instead of the old (failing) Travis build
=> docs: Update build badge in README

default.nix
Required for builds where the full repository isn't available (e.g. from a tarball).
=> chore(build): Allow passing in a specific commit hash when building

prepare-image/prepare-image.nix
This is required by common patterns in shell scripts.
There are some caveats around this. Adding logic to filter whether coreutils is included in an image would slow down the Nix evaluation, so the link is currently created even in cases where it doesn't point to anything.
Fixes #109
=> feat(prepare-image): Ensure /usr/bin/env is always present

docs/src/run-your-own.md
While setting up a Nixery dev env on a new machine, I realized
that the "run your own" instructions were out of sync. This is my
modest attempt in fixing that :)
The instructions were not up-to-date (they didn't mention
the different storage backends, and some variables were
tagged as optional while they were mandatory). With this
update, they should (hopefully) be more accurate,
I also added instructions if someone wants to run Nixery
outside of the container image (I found it convenient when
working on Nixery's code).
=> docs: update installation instructions

config/config.go
The error message shows the wrong variable name, which might
be confusing for new users.
(And to not-so-new users with a flaky memory😅)
=> chore: fix env var name in error message

docs/src/nixery.md
Afaict, the arm64 metapackage (discussed in issue #13 ) isn't mentioned anywhere in the docs yet.
I don't know if there are any other metapackages, but arm64 and shell are the only ones I'm aware of.
If there are any more, it might make more sense to move this info to a separate page about metapackages.
=> mention arm64 metapackage

prepare-image/prepare-image.nix
Hi!
Some programs fail when /tmp doesn't exist:
- terraform
- anything using mktemp and similar helpers
It's trivial to address (just `mkdir /tmp`, or set `TMPDIR`, or mount an ephemeral volume on /tmp) but it would also be nice if stuff like `docker run nixery.dev/shell/terraform` worked out of the box.
Creating /tmp seems super easy; there might be a better place to do it but this one seemed simple enough.
This PR should really be just 1 line; but I updated the comments around it otherwise they wouldn't have quite the same meaning. I hope that's OK; let me know otherwise, happy to tweak/rephrase things!
=> feat: add /tmp

builder/builder.go, manifest/manifest.go
Two minor "quality of life" improvements:
- automatically set SSL_CERT_FILE environment variable,
so that programs relying on OpenSSL for certificate
validation can actually validate certificates
(the certificates are included no matter what since
we add the "cacert" package to all images)
- if the requested image includes an interactive shell
(e.g. if it includes the "shell" metapackage), set
the image Cmd to "bash", which allows to execute
"docker run nixery.dev/shell" and get a shell)
I'm happy to split this PR in two if you'd like, but
since both features touch the Config structure and are
rather small, I thought it would make sense to bundle
them together.
To give you a bit more context around this PR:
I've been using Nixery extensively in live demos,
teaching environments, etc. and …
=> feat: set SSL_CERT_FILE and provide a Cmd

README.md, docs/src/nixery.md, docs/src/run-your-own.md
The Nixery main Git repo has moved from [github.com/**google**/nixery](https://github.com/google/nixery) to [github.com/**tazjin**/nixery](https://github.com/tazjin/nixery).
So change
- respective URL targets in the README
- respective URL targets on the https://nixery.dev/ website
- ~~the package path of the Nixery Go module~~
I'm not quite sure how to test the latter, so I hope CI would catch any breakage this might cause.
=> Update GitHub namespace
